# Site settings
title: Infinite
smalltalk: "the untroubled musings of a clouded mind"
description: > # My blog Powred by jekyll
baseurl: "/Blog" # the subpath of your site, e.g. /blog/
paginate: 5
url: "http://davidpeterko.github.io/Blog" # the base hostname & protocol for your site
twitter_username: wutangcamber 
github_username: davidpeterko
facebook_username: nopenottodaylol
portfolio_url: http://davidpeterko.github.io

# Build settings
markdown: kramdown
