# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji
  
# Site settings
title: "Infinite"
description: > # this means to ignore newlines until "email:"
  A blog dedicated to my sporadic thoughts. 

email: davidpeterko@gmail.com 
#blog logo
logo: "/assets/images/df_logo.jpg"
# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'David Ko'
author: 'David Ko'
author_image: 

paginate:	5

url: "http://davidpeterko.github.io/Blog" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/wutangcamber
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://facebook.com/nopenottodaylol
    desc: Connect with me facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/davidpeterko
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:


